### ISSUE TITLE
Bundled JS files still downloaded separately

### ISSUE THREAD

**Issue by luke-denton-aligent** [antonkril/magento-rjs-config#1]
Hi,

Thanks for your work on this configuration and instructions on using the RequireJS optimizer.

I have an issue with files that are included in the bundle still being downloaded as before. It seems that the only change is that the file will get downloaded twice (once as part of the bundle, and once as part of the way RequireJS normally works). Is there some further configuration required to tell RequireJS that the files have already been downloaded?

**Comment by antonkril** [comment]
No. This is not normal behavior. Do you get any JS errors in console?

**Comment by jissereitsma** [comment]
@luke-denton-aligent Is this issue still open?

**Comment by luke-denton-aligent** [comment]
@jissereitsma I'm unaware if this issue is still persistent. I removed the config after initially finding that it didn't work as expected.

**Comment by antonkril** [comment]
The repo is not supported. Closing.
