### ISSUE TITLE
Using experimental es2015+ uglify-js harmony branch with Magento

### ISSUE THREAD

**Issue by Vinai** [antonkril/magento-rjs-config#5]
Has someone tried using the experimental https://www.npmjs.com/package/uglify-js-es6#harmony with this build.js?
It would be nice to be able to use a better optimization level than `'none'`.
I'm looking for responses like "I made it work but it took weeks|days|hours and it's brittle" to "don't try, it's a hell hole and won't work"...

**Comment by rossmc** [comment]
Rather than using `'none'`, I've found using the es5 uglify that comes with rjs works well.

    optimize: 'uglify',
    preserveLicenseComments: false,

Does Magento use any es6 in it's core?

**Comment by antonkril** [comment]
`optimize: "none"` was there for development purposes only. Commented it out
