### ISSUE TITLE
Support javaScript mixins

### ISSUE THREAD

**Issue by kweij** [antonkril/magento-rjs-config#7]
Hi Anton,

I know this gist is deprecated and I'm trying to use the guide for Magento 2.3 (https://devdocs.magento.com/guides/v2.3/performance-best-practices/advanced-js-bundling.html) to bundle the javascript, but I run into the problem that mixins aren't loaded for components that I extended.

I've tried including the 'mixins!Magento_Ui/js/lib/knockout/bindings/bootstrap' assets in the modules right after 'Magento_Ui/js/lib/knockout/bindings/bootstrap', for example. But this seems to cause to not load and stop JavaScript. I can't just leave out the components that have mixins assigned to them, because then I would need to strip out any component that get's extends by any (core, own, third party) module. Do you think it can be achieved at all? And perhaps how?

Perhaps I should direct Adrew Levine about this, though, but this gist is my only lead so far.

**Comment by antonkril** [comment]
The repository is deprecated. Closing.
